### PR TITLE
Adding Rounding Function for RRDTool

### PR DESCRIPTION
**Pull request by TheWitness**
I was playing with a Cacti Graph Template the other day and saw the time related averaging that is inherit in RRDTool making values that should appear integers appear as floats on the graph.  So, I'm like, hey "I'll just use a rounding function, that'll work".  Only to find that it was missing.

Love to tool been using it for almost two decades, though I don't consider myself an expert.  Here is a little contribution from me.  Nothing magical, just a rounding function.  Related to the following bug report.

https://github.com/oetiker/rrdtool-1.x/issues/975

Thank you Tobi for all you have done for the monitoring community.  Be well.

### CODE REVIEW

**Comment by netniV** [comment]
Always a useful thing to have

**Comment by netniV** [comment]
Could probably do with allowing a parameter for the number of places to round by?

**Comment by TheWitness** [comment]
You can achieve the same results by first multiplying by XX rounding, and diving by XX.  So, it can be achieved without modifying this pull.  I'll defer to @oetiker and what he wants to see.

**Comment by oetiker** [comment]
since neither ceil nor floor offer that precision, I would go for the simple version

**Comment by oetiker** [comment]
I will release 1.7.2 prior to adding this functionality

**Pull request merged**
