### PR TITLE
add releasee tests to travis and bump version number for rerelease wi…

### PR DESCRIPTION
**Pull request by oetiker**
…th fixed makefiles

### CODE REVIEW

**Comment by c72578** [comment]
Should the following be updated too in configure.ac?
NUMVERS=1.7001
->
NUMVERS=1.7002

**Comment by oetiker** [comment]
hmm all these numbers should be generated from the VERSION file ...

**Comment by c72578** [comment]
Yes, this would simplify things, if these numbers are generated from the VERSION file.
For consistency, the same NUMVERS should also be used in `win32/rrd_config.h`:
NUMVERS=1.72
->
NUMVERS=1.7002

**Comment by c72578** [comment]
/bin/bash: ps2pdf: command not found
https://travis-ci.org/oetiker/rrdtool-1.x/builds/489975897?utm_source=github_status&utm_medium=notification

**Pull request merged**
