### PR TITLE
fix some grammar errors and typos

### PR DESCRIPTION
**Pull request by diphuaji**
fix some grammar errors and typos

### CODE REVIEW

**Comment by oetiker** [comment]
your patch does not apply to master ...

**Comment by oetiker** [comment]
@diphuaji can you please remove the conflicts from your patch ?

**Comment by diphuaji** [comment]
@oetiker I have merged the conflicts. If there is anything I still need to do, please tell me.

**Comment by oetiker** [comment]
perfect ... thanks

**Pull request merged**
