### PR TITLE
Added resolution (step) option to rrdcached FETCH(BIN) commands.

### PR DESCRIPTION
**Pull request by mindnever**
This patch adds -r option to the FETCH and FETCHBIN commands.

### CODE REVIEW

**Comment by oetiker** [comment]
nice ... 

please update src/rrd_client.c, src/rrd_fetch.c and doc/rrdcached.pod accordingly.

**Comment by oetiker** [comment]
ping

**Comment by mindnever** [comment]
Sorry for not acking. Will do, just had some other things on my mind :)

**Comment by oetiker** [comment]
I'm afraid this will not make it into 1.5 like that

**Pull request closed without merging**
