### PR TITLE
Fix bounds in rrd_xport fix #913 and #928

### LINKED ISSUE #913: Inconsistency in time for values
There seems to be an inconsistency with which value is displayed at what time between the xport and dump commands. The times and values match in 1.4.8, but not in 1.5.0, 1.6.0 or the newest 1.7.0 from the repository.

Here are some examples using the same rrd file for 3 of the versions. Note: Newer versions need the -t/--showtime argument to show the time. And i've censored the e-mail, for the sake of online crawlers for spam.

1.4.8:
```
kbj@kbj-dev ~/git $ rrdtool | head -n1
RRDtool 1.4.8  Copyright 1997-2013 by Tobias Oetiker <***@***>
kbj@kbj-dev ~/git $ rrdtool xport --start 1540207800 --end 1540208700 DEF:ns10=/tmp/ns10.rrd:ns10:AVERAGE XPORT:ns10 | grep '<row>'
    <row><t>1540208100</t><v>9.3745082714e-01</v></row>
    <row><t>1540208400</t><v>1.8551453360e+02</v></row>
    <row><t>1540208700</t><v>NaN</v></row>
    <row><t>1540209000</t><v>NaN</v></row>
kbj@kbj-dev ~/git $ rrdtool dump /tmp/ns10.rrd | grep '2018-10-22' | grep '<row>' | sort -n | uniq | tail -n3
			<!-- 2018-10-22 13:30:00 CEST / 1540207800 --> <row><v>3.5072563673e+01</v></row>
			<!-- 2018-10-22 13:35:00 CEST / 1540208100 --> <row><v>9.3745082714e-01</v></row>
			<!-- 2018-10-22 13:40:00 CEST / 1540208400 --> <row><v>1.8551453360e+02</v></row>
```

1.6.0:
```
kbj@kbj-dev2:~/git$ rrdtool | head -n1
RRDtool 1.6.0  Copyright by Tobias Oetiker <***@***>
kbj@kbj-dev2:~/git$ rrdtool xport -t --start 1540207800 --end 1540208700 DEF:ns10=/tmp/ns10.rrd:ns10:AVERAGE XPORT:ns10 | grep '<row>'
    <row><t>1540207800</t><v>9.3745082714e-01</v></row>
    <row><t>1540208100</t><v>1.8551453360e+02</v></row>
    <row><t>1540208400</t><v>NaN</v></row>
kbj@kbj-dev2:~/git$ rrdtool dump /tmp/ns10.rrd | grep '2018-10-22' | grep '<row>' | sort -n | uniq | tail -n3
			<!-- 2018-10-22 13:30:00 CEST / 1540207800 --> <row><v>3.5072563673e+01</v></row>
			<!-- 2018-10-22 13:35:00 CEST / 1540208100 --> <row><v>9.3745082714e-01</v></row>
			<!-- 2018-10-22 13:40:00 CEST / 1540208400 --> <row><v>1.8551453360e+02</v></row>
```

1.7.0 (newest from git):
```
kbj@kbj-dev2:~/git/GPL/debian/rrdtool-1.x$ git log | head -n1
commit ecf80e67294a5089ceee0d51924eca16622aa655
kbj@kbj-dev2:~/git/GPL/debian/rrdtool-1.x$ src/rrdtool | head -n1
RRDtool 1.7.0  Copyright by Tobias Oetiker <***@***>
kbj@kbj-dev2:~/git/GPL/debian/rrdtool-1.x$ src/rrdtool xport -t --start 1540207800 --end 1540208700 DEF:ns10=/tmp/ns10.rrd:ns10:AVERAGE XPORT:ns10 | grep '<row>'
    <row><t>1540207800</t><v>9.3745082714e-01</v></row>
    <row><t>1540208100</t><v>1.8551453360e+02</v></row>
    <row><t>1540208400</t><v>NaN</v></row>
kbj@kbj-dev2:~/git/GPL/debian/rrdtool-1.x$ src/rrdtool dump /tmp/ns10.rrd | grep '2018-10-22' | grep '<row>' | sort -n | uniq | tail -n3
			<!-- 2018-10-22 13:30:00 CEST / 1540207800 --> <row><v>3.5072563673e+01</v></row>
			<!-- 2018-10-22 13:35:00 CEST / 1540208100 --> <row><v>9.3745082714e-01</v></row>
			<!-- 2018-10-22 13:40:00 CEST / 1540208400 --> <row><v>1.8551453360e+02</v></row>
```

As you can see, the 9.37[..] value is set to the [..]8100 time in the dump output on all 3 examples, but it's only on the same time for xport in the 1.4.8 example. The newer versions has that value set to the [..]7800 time when using xport.

In #805 it's indicated that the timestamp is supposed to be the end of the time period, so i would think that it might have been accidentally starting to show the timestamp for the beginning of the time period. I would assume it happened in the 1.5.0 rewrite of xport that was mentioned in #672.

I'm also unclear as to whether the start and end values are supposed to be both inclusive or exclusive and whether they should match the end time for each period or what. If this is going to be revisited, i'd ask that this would also be considered, so it'd be consistent or at least on purpose, so it hopefully will stay that way. In the newer versions, it seems to include the timestamps that match the start value, but not timestamps that match the end value.

### PR DESCRIPTION
**Pull request by Titan-C**
rrdxport needs to provide enough data points in its output for the
receiving client to be able to reproduce the graphs generated by rrdgraph.

- The start time pointer needs to be at the start of the interval that
  contain the query start time. For the function that retrieves the data.
  On output the returned start timestamp is > than query timestamp.
- SV export was missing the end boundary

This aims to fix issue #913 and extends on #928

Using the script of https://github.com/oetiker/rrdtool-1.x/issues/913#issuecomment-473988007, this changes generate this new output.

All necessary values, associated for every timestamp are provided, in XML/JSON export as in the SV, to accurately reproduce an graph in the queried interval.

Still needs to be fixed.
- [x] TEST
- [x] Docs, particularly changes in  #931

Example output below:
```bash
DATABASE NATIVE RESOLUTION
Query start:  1500000005 : Fri Jul 14 04:40:05 CEST 2017
Query end  : 1500000072 : Fri Jul 14 04:41:12 CEST 2017
RRD XPORT
{ "about": "RRDtool graph JSON output",
  "meta": {
    "start": 1500000010,
    "end": 1500000080,
    "step": 10,
    "legend": [
      "",
      ""
          ]
     },
  "data": [
    [ "1500000010",1.0000000000e+01, 1.1000000000e+01 ],
    [ "1500000020",2.0000000000e+01, 2.1000000000e+01 ],
    [ "1500000030",3.0000000000e+01, 3.1000000000e+01 ],
    [ "1500000040",4.0000000000e+01, 4.1000000000e+01 ],
    [ "1500000050",5.0000000000e+01, 5.1000000000e+01 ],
    [ "1500000060",6.0000000000e+01, 6.1000000000e+01 ],
    [ "1500000070",7.0000000000e+01, 7.1000000000e+01 ],
    [ "1500000080",8.0000000000e+01, 8.1000000000e+01 ]
  ]
}
RRD CSV
0x0
"time","first","second"
1500000010,"1.0000000000e+01","1.1000000000e+01"
1500000020,"2.0000000000e+01","2.1000000000e+01"
1500000030,"3.0000000000e+01","3.1000000000e+01"
1500000040,"4.0000000000e+01","4.1000000000e+01"
1500000050,"5.0000000000e+01","5.1000000000e+01"
1500000060,"6.0000000000e+01","6.1000000000e+01"
1500000070,"7.0000000000e+01","7.1000000000e+01"
1500000080,"8.0000000000e+01","8.1000000000e+01"
``` 
For resampled data the the behaviour is also fixed:
```bash
DATABASE RESAMPLED RESOLUTION
Query start:  1500000005 : Fri Jul 14 04:40:05 CEST 2017
Query end  : 1500000072 : Fri Jul 14 04:41:12 CEST 2017
RRD XPORT
{ "about": "RRDtool graph JSON output",
  "meta": {
    "start": 1500000030,
    "end": 1500000090,
    "step": 30,
    "legend": [
      "",
      ""
          ]
     },
  "data": [
    [ "1500000030",3.0000000000e+01, 3.1000000000e+01 ],
    [ "1500000060",6.0000000000e+01, 6.1000000000e+01 ],
    [ "1500000090",null, null ]
  ]
}
RRD CSV
0x0
"time","first","second"
1500000030,"3.0000000000e+01","3.1000000000e+01"
1500000060,"6.0000000000e+01","6.1000000000e+01"
1500000090,"NaN","NaN"
```
For queries within 2 timestamps only one value is returned, and metadata reflects the output coherently.
```bash
DATABASE QUERY WITHIN MEASUREMENTS
Query start:  1500000002 : Fri Jul 14 04:40:02 CEST 2017
Query end  : 1500000009 : Fri Jul 14 04:40:09 CEST 2017
RRD XPORT
{ "about": "RRDtool graph JSON output",
  "meta": {
    "start": 1500000010,
    "end": 1500000010,
    "step": 10,
    "legend": [
      "",
      ""
          ]
     },
  "data": [
    [ "1500000010",1.0000000000e+01, 1.1000000000e+01 ]
  ]
}
RRD CSV
0x0
"time","first","second"
1500000010,"1.0000000000e+01","1.1000000000e+01"
```

### CODE REVIEW

**Comment by oetiker** [comment]
thanks

**Comment by Titan-C** [comment]
Hi,
How does it go on? Does this get merged, do you need something else?
I was also wondering if it would be pertinent to change in the XML/JSON export to:

```diff
@@ -750,10 +750,10 @@ static int rrd_xport_format_xmljson(
     } else {
         if (json) {
             snprintf(buf, sizeof(buf), "    \"%s\": %lld,\n", META_START_TAG,
-                     (long long int) start + step);
+                     (long long int) start);
         } else {
             snprintf(buf, sizeof(buf), "    <%s>%lld</%s>\n", META_START_TAG,
-                     (long long int) start + step, META_START_TAG);
+                     (long long int) start, META_START_TAG);
         }
     }
     addToBuffer(buffer, buf, 0);
```
That would only have an influence in the metadata section.

**Comment by oetiker** [comment]
> Hi,
> How does it go on? 

sorry got distracted :)

> That would only have an influence in the metadata section.

why would you change the metadata section?

**Comment by Titan-C** [comment]
> why would you change the metadata section?

Well, now in the metadata start and end timestamps also mark the bounds
of all the timestamped values returned in the data array. That is, it is
a closed interval description.

For that reason the amount of data rows would need to be calculated as:

(start-end)/step + 1

start==first_timestamp, and the validity of the first interval is
[start-step; start[.

If I change the metadata section as proposed in the diff. The amount of
data rows is calculated:

(start-end)/step

In this case, start+step==first_timestamp, and the validity of the first
interval is [start; start+step[.

It is just a matter of convention. That's why I was unsure on that change.

**Comment by oetiker** [comment]
no the the metadata should represent what is in the xport

note that the value stored in a slot are 'valid' for the time from start to just before end ...

**Pull request merged**
