### PR TITLE
Add --utc to graph option.

### PR DESCRIPTION
**Pull request by jyavenard**
Allow to generate a graph as if the current timezone was UTC (e.g set TZ=UTC).
This allow to easily calculate daily average ranging from midgnight to midnight rather that say the last 24 hours.

### CODE REVIEW

**Comment by netniV** [comment]
This patch is seven years old! :)  

But I like the idea, if I was to target this towards the current version, would you commit it?  Will have to try to co-author it as @jyavenard did the original work.

**Comment by jyavenard** [comment]
FWIW, I still use it daily, and I've been updating it whenever a new version of rrdtool came out

**Comment by netniV** [comment]
Maybe the better course of action then is to close and recreate the PR 👍   I'll chip my vote in for it when it's reposted if you tag me

**Comment by oetiker** [comment]
"fixing" this one is fine

**Pull request closed without merging**
