### PR TITLE
use systemd macros for rrdcached in rpm spec file

### PR DESCRIPTION
**Pull request by tvestelind**
I've added:
* a variable to control whether or not to build for systemd
* systemd-provided macros in the RPM spec-file according what Fedora
  recommends here: 
  - https://fedoraproject.org/wiki/Packaging:Scriptlets?rd=Packaging:ScriptletSnippets#Systemd and 
  - https://fedoraproject.org/wiki/Packaging:Systemd#Packaging

Signed-off-by: Tomas Vestelind <tomas.vestelind@gmail.com>

### CODE REVIEW

**Comment by oetiker** [comment]
thanks!

**Comment by tvestelind** [comment]
No problem :)

I just want to add that I haven't really tried that systemd macro. We define that macro differently in our version of this spec file so if you could look closely at that part it would be great :)

**Comment by oetiker** [comment]
well others willl I am not building RPMs myself

**Comment by tvestelind** [comment]
Ok, good. Thank :)

**Pull request merged**
