### PR TITLE
Update to PR #915

### PR DESCRIPTION
**Pull request by netniV**
I believe this new code should handle the multiple delimiter split better as discussed in #914

### CODE REVIEW

**Comment by oetiker** [comment]
thanks!

**Comment by c72578** [comment]
gcc shows the following warning:
<pre>
rrd_graph.c: In function ‘graph_title_split’:
rrd_graph.c:6203:43: warning: iteration 4 invokes undefined behavior [-Waggressive-loop-optimizations]
             int delim_size = strlen(delims[i]);
                                     ~~~~~~^~~
rrd_graph.c:6200:9: note: within this loop
         for(unsigned int i=0; i < sizeof(delims); i++)
         ^~~
</pre>

**Comment by c72578** [comment]
`sizeof(delims)` determines the size of delims in bytes, which can be n=16 (4x4) on 32-bit and n=32 (4x8) on 64-bit systems. So we need:
`for(unsigned int i=0; i < sizeof(delims) / sizeof(delims[0]); i++)`
instead of
`for(unsigned int i=0; i < sizeof(delims); i++)`

I will submit a PR.

**Comment by netniV** [comment]
Ah, yes.  Please do.

**Comment by c72578** [comment]
PR created: https://github.com/oetiker/rrdtool-1.x/pull/919

**Comment by oetiker** [comment]
would that fail it the delim strings were of different size ?

**Comment by c72578** [comment]
@netniV Have you got a minimal rrdtool example by hand for testing the multiple delimiter split? I have just been testing, but did not get the expected results yet.

**Comment by netniV** [comment]
@c72578 Thanks! I was going to post that I use Cacti to generate my tests but I could have got the command lines.  Unfortunately, day job got in the way and you'd resolved it before I got back to you 👍

**Pull request merged**
